---
- hosts: transactors
  roles:
    - { role: transactor }
    - { role: dynamodb_local, become: yes, become_user: "root" }
    - { role: grpc, grpc_checkout: "be223358795b645416e801727f4d3fcad3d73964" }
