---
- hosts: transactor-client-provisioning
  roles:
    - transactor

  tasks:
  - name: install pip
    apt: name=python-pip state=present

  - name: install libjpeg-dev
    apt: name=libjpeg-dev state=present

  - name: install libpng-dev
    apt: name=libpng-dev state=present

  - name: update to latest pip
    pip: name=pip state=latest
    
  - name: checkout mediachain
    git: repo=https://github.com/mediachain/mediachain.git dest=/home/ubuntu/mediachain

  - name: set ownership of mediachain src tree
    file: path=/home/ubuntu/mediachain owner=ubuntu group=ubuntu recurse=yes

  - name: checkout mediachain-client
    git: repo=https://github.com/mediachain/mediachain-client.git dest=/home/ubuntu/mediachain-client

  - name: set ownership of mediachain-client src tree
    file: path=/home/ubuntu/mediachain-client owner=ubuntu group=ubuntu recurse=yes

  - name: prepare /mnt/data
    file: path=/mnt/data state=directory owner=ubuntu group=ubuntu
