---
- hosts: transactor-provisioning
  tasks:
  - name: update system
    apt: upgrade=yes
  - name: setup git ppa repo
    apt_repository: repo=ppa:git-core/ppa
  - name: install git
    apt: name=git state=present update_cache=true
  - name: checkout mediachain
    git: repo=https://github.com/mediachain/mediachain.git dest=/home/ubuntu/mediachain
  - name: run setup script
    shell: /home/ubuntu/mediachain/scripts/ubuntu-setup.sh && touch /home/ubuntu/.ubuntu-setup
    args:
      creates: /home/ubuntu/.ubuntu-setup
  - name: set ownership of mediachain src tree
    file: path=/home/ubuntu/mediachain owner=ubuntu group=ubuntu recurse=yes
  - name: prepare /mnt/transactor
    file: path=/mnt/transactor state=directory owner=ubuntu group=ubuntu

