---
- name: install ntp
  apt: name=ntp state=present
  become: yes

- name: start ntp service
  service: name=ntp enabled=true state=started
  become: yes
  
- name: setup git ppa repo
  apt_repository: repo=ppa:git-core/ppa
  become: yes
  become_user: "root"

- name: install git
  apt: name=git state=present update_cache=true
  become: yes
  become_user: "root"

- name: install daemon
  apt: name=daemon state=present
  become: yes

