galaxy_info:
  author: Mediachain Labs Team
  description: > 
    Provides the dependencies needed by the mediachain transactor
  company: Mediachain Labs
  license: MIT
  min_ansible_version: 1.8.1
  platforms:
    - name: Ubuntu
      versions:
        - trusty
dependencies:
  - { role: jpnewman.java, tags: ["init"], become: yes, become_user: "root" }
  - { role: milinda.sbt, become: yes, become_user: "root" }