- block:
  - name: install grpc base dependencies
    apt: name={{item}}
    with_items:
        - libtool
        - autoconf

  - name: clone grpc git repo
    git: repo={{ grpc_repo }}
         dest={{ grpc_source_dir }}
         version={{ grpc_checkout }}

  - name: install grpc python module
    shell: >
      make clean && \
      pip install -r requirements.txt && \
      env GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install . && \
      rm -f {{ grpc_source_dir }}/.grpc_python_version_installed_* && \
      touch "{{ grpc_source_dir }}/.grpc_python_version_installed_{{ grpc_checkout }}"
    args:
      chdir: "{{ grpc_source_dir }}"
      creates: "{{grpc_source_dir}}/.grpc_python_version_installed_{{ grpc_checkout }}"

  - name: build and install grpc
    shell: > 
      make clean && \
      make install && \
      (cd third_party/protobuf && make install && make clean) && \
      rm -f {{ grpc_source_dir }}/.grpc_version_installed_* && \
      touch "{{ grpc_source_dir }}/.grpc_version_installed_{{grpc_checkout}}"
    args:
      chdir: "{{ grpc_source_dir }}"
      creates: "{{ grpc_source_dir }}/.grpc_version_installed_{{grpc_checkout}}"

  become: yes
  become_user: root